blueprint:
  name: Voice - Set Voice Assistant Personality Trait
  description: >
    This blueprint sets a personality trait level for your voice assistant by updating
    an existing input_number helper. When a voice command is issued (for example,
    "Set sarcasm level to 7"), your LLM will supply the new value for the trait.
  domain: script
  homeassistant:
    min_version: 2025.0.0
  input:
    trait_entity:
      name: Trait Entity
      description: "Select the input_number entity for the personality trait (e.g., input_number.sarcasm)."
      selector:
        entity:
          domain: input_number
    new_value_prompt:
      name: New Value Prompt
      description: "Instruction for the LLM: what number should be provided for the trait?"
      selector:
        text:
          multiline: true
      default: "Provide a whole number between 0 and 10 as the trait level."
mode: parallel
max_exceeded: silent
fields:
  new_value:
    name: New Value
    description: !input new_value_prompt
    selector:
      number:
        min: 0
        max: 10
    required: true
sequence:
  - service: input_number.set_value
    target:
      entity_id: !input trait_entity
    data:
      value: "{{ new_value }}"
  - stop: "The trait {{ trait_entity }} has been updated successfully to {{ new_value }}."
