blueprint:
  name: Voice - Set Voice Assistant Personality Trait (GLaDOS)
  description: >
    This script sets a personality trait level for GLaDOS or another voice assistant.
    IMPORTANT: When calling this script via voice, you MUST include a numeric value between 0-10.
    Say phrases like "Set sarcasm level to 7" or "Change GLaDOS sarcasm to 3".
    The script requires 'new_value' parameter to work properly.
  domain: script
  input:
    trait_entity:
      name: Trait Entity
      description: "Select the input_number entity for the personality trait (e.g., input_number.sarcasm)."
      selector:
        entity:
          domain: input_number
    new_value:
      name: New Value
      description: "REQUIRED: The new level for the trait (number between 0-10). When using voice, say a phrase like 'Set sarcasm level to 7'."
      default: 5
      selector:
        number:
          min: 0
          max: 10
          step: 1
          mode: slider

mode: parallel
max_exceeded: silent
sequence:
  - variables:
      value_to_set: "{{ new_value | float }}"
  - service: input_number.set_value
    target:
      entity_id: !input trait_entity
    data:
      value: "{{ value_to_set }}"
  - stop: "The trait {{ trait_entity }} has been updated successfully to {{ value_to_set }}."
