blueprint:
  name: Voice - Set Voice Assistant Personality Trait
  description: >
    This blueprint sets a personality trait by updating an existing input_number helper.
    When used with your OpenAI GPT-4 integration, the LLM is expected to provide the new value
    for the trait based on the prompts defined below.
  domain: script
  homeassistant:
    min_version: 2025.0.0
  input:
    trait_entity:
      name: Trait Entity
      description: "Select the input_number entity for the personality trait (for example, input_number.sarcasm)."
      selector:
        entity:
          domain: input_number
    prompt_settings:
      name: Prompt Settings for LLM
      description: >
        (Optional) Customize the instructions that the LLM will see for supplying each input.
      default:
        new_value_prompt: "Provide a whole number between 0 and 10 representing the trait level."
      selector:
        object:
          properties:
            new_value_prompt:
              name: New Value Prompt
              description: "Instruction that guides the LLM on what the new trait level should be."
              selector:
                text:
                  multiline: true
    new_value:
      name: New Value
      description: >
        {% if prompt_settings.new_value_prompt %}
          {{ prompt_settings.new_value_prompt }}
        {% else %}
          Provide a whole number between 0 and 10 representing the trait level.
        {% endif %}
      selector:
        number:
          min: 0
          max: 10
          step: 1
          mode: slider

script:
  mode: parallel
  max_exceeded: silent
  sequence:
    - service: input_number.set_value
      target:
        entity_id: !input trait_entity
      data:
        value: "{{ new_value }}"
    - stop: "The trait {{ trait_entity }} has been updated successfully to {{ new_value }}."

