blueprint:
  name: Voice - Set Voice Assistant Personality Trait
  description: >
    This script sets a personality trait level (like sarcasm) to a value between 0 and 10.
    You must provide a 'new_value' parameter when calling this script.
    Example usage: "Set sarcasm level to 7" or "Change GLaDOS sarcasm to 3".
  domain: script
  input:
    trait_entity:
      name: Trait Entity
      description: "Select the input_number entity for the personality trait (e.g., input_number.sarcasm)."
      selector:
        entity:
          domain: input_number
    new_value:
      name: New Value
      description: "The new level for the trait. Must be a number between 0 and 10."
      required: true
      example: 7
      selector:
        number:
          min: 0
          max: 10
          step: 1
          mode: slider

mode: parallel
max_exceeded: silent
sequence:
  - variables:
      value_to_set: >
        {% if new_value is defined %}
          {{ new_value | float }}
        {% else %}
          {{ 5 }}
        {% endif %}
  - service: input_number.set_value
    target:
      entity_id: !input trait_entity
    data:
      value: "{{ value_to_set }}"
  - stop: >
      {% if new_value is defined %}
        The trait {{ trait_entity }} has been updated successfully to {{ new_value }}.
      {% else %}
        Warning: No value was provided. The trait was set to a default value of 5.
      {% endif %}
